apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: testapi-project
  namespace: argocd
spec:
  namespaceResourceWhitelist:
  - group: ""        # "" indicates the core group
    kind: Pod
  - group: ""        # "" indicates the core group
    kind: Service
  - group: "apps"    # "apps" is the group for Deployment
    kind: Deployment
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: myproject
  source:
    repoURL: https://github.com/Rendani-M/kubeApi.git
    path: devfiles
    targetRevision: HEAD
  destination: 
    server: https://kubernetes.default.svc
    namespace: testApiNS 
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
